name: CI



on: 

  [push, workflow_dispatch]



jobs:

  build:

    runs-on: ubuntu-22.04  # Specify the Ubuntu runner



    steps:

    - name: Checkout Repository

      uses: actions/checkout@v3



    - name: Download ngrok

      run: |

        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz

        tar -xvzf ngrok-v3-stable-linux-amd64.tgz

        sudo mv ngrok /usr/local/bin/ngrok



    - name: Set ngrok auth token

      run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}



    - name: Install xrdp for RDP

      run: |

        sudo apt update

        sudo apt install xrdp -y

        sudo systemctl enable xrdp

        sudo systemctl start xrdp

        sudo ufw allow 3389



    - name: Create Tunnel with ngrok

      run: |

        ngrok tcp 3389

